### ISSUE TITLE
Rename repo to "lda"?

### ISSUE THREAD

**Issue by dselivanov** [slycoder/R-lda#9]
Why depreciated? :-) it well maintained and it is the best package among which I tried. 
R-lda-depreciared  name confuses a little bit :-)

**Comment by RyanRosario** [comment]
I agree. I asked a while back and I think Jonathan originally wanted to port everything to Julia and deprecate the R version.

**Comment by slycoder** [comment]
Thanks for the vote of confidence!   I'll rename this repo to R-lda.  I had indeed originally planned to rewrite everything but upon reflection gradual improvement may be the better approach.
